dbTier: db-f1-micro
dbAutoresizeDisk: false
limitsCpu: 500m
limitsMemory: 512Mi
requestsCpu: 200m
requestsMemory: 256Mi
kafkaPool: nav-dev
journalpostHost: dokarkiv-q2.dev-fss-pub.nais.io
journalpostApi: https://dokarkiv-q2.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
journalpostScope: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
