apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fia-dokument-publisering
  namespace: pia

spec:
  image: {{image}}

  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
    timeout: 60

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
