apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pia
  name: fia-dokument-publisering
  namespace: pia

spec:
  image: {{image}}
  resources:
    limits:
      cpu: {{limitsCpu}}
      memory: {{limitsMemory}}
    requests:
      cpu: {{requestsCpu}}
      memory: {{requestsMemory}}
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: fia-arbeidsgiver
    outbound:
      rules:
        - application: pia-pdfgen
      external:
        - host: {{journalpostHost}}
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: {{dbTier}}
        diskAutoresize: {{dbAutoresizeDisk}}
        databases:
          - name: fia-dokument-publisering-db
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: PIA_PDFGEN_URL
      value: http://pia-pdfgen
    - name: JOURNALPOST_V1_URL
      value: {{journalpostApi}}
    - name: JOURNALPOST_SCOPE
      value: {{journalpostScope}}
